spring.application.name=SGI

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sgi_db
spring.datasource.username=postgres
spring.datasource.password=Aymane@4123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Server Configuration
server.port=8080
server.servlet.context-path=

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationMustBeAtLeast256BitSGI2024
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.SSS.SGI=DEBUG

