-- =====================================================================
-- V1 — Schéma de référence (baseline)
--
-- Ce fichier reprend à l'identique le schéma tel qu'il était produit
-- par `spring.jpa.hibernate.ddl-auto=update` avant l'introduction de
-- Flyway. Il permet de reconstruire une base vierge de zéro.
--
-- À partir d'ici, toute évolution du schéma passe par une nouvelle
-- migration Vn__description.sql : `ddl-auto` est passé à `validate`,
-- Hibernate ne modifie plus la base lui-même.
-- =====================================================================



CREATE TYPE public.statut_imputation AS ENUM (
    'EN_ATTENTE',
    'VALIDEE',
    'REJETEE'
);

CREATE TABLE public.absence (
    date_debut date NOT NULL,
    date_envoi_justificatif date,
    date_fin date NOT NULL,
    nombre_jours double precision NOT NULL,
    date_demande timestamp(6) without time zone NOT NULL,
    date_validation timestamp(6) without time zone,
    id_absence bigint NOT NULL,
    id_employe bigint NOT NULL,
    id_manager_validateur bigint,
    statut character varying(20) NOT NULL,
    type_absence character varying(40) NOT NULL,
    commentaire_employe character varying(500),
    motif_rejet character varying(500),
    justificatif_url character varying(255),
    CONSTRAINT absence_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'VALIDEE'::character varying, 'REJETEE'::character varying, 'ANNULEE'::character varying])::text[]))),
    CONSTRAINT absence_type_absence_check CHECK (((type_absence)::text = ANY ((ARRAY['CONGE_PAYE'::character varying, 'RTT'::character varying, 'CONGE_EXCEPTIONNEL'::character varying, 'MALADIE'::character varying, 'CONGE_MATERNITE_PATERNITE'::character varying, 'SANS_SOLDE'::character varying])::text[])))
);

ALTER TABLE public.absence ALTER COLUMN id_absence ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absence_id_absence_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.affectation (
    date_affectation date,
    taux_affectation numeric(5,2) NOT NULL,
    id_collaborateur bigint NOT NULL,
    id_projet bigint NOT NULL
);

CREATE TABLE public.budget_projet (
    budget_initial numeric(12,2) NOT NULL,
    tjm numeric(8,2) NOT NULL,
    id_projet bigint NOT NULL
);

CREATE TABLE public.client (
    id_client bigint NOT NULL,
    nom_client character varying(100) NOT NULL
);

ALTER TABLE public.client ALTER COLUMN id_client ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_client_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.collaborateur (
    id_collaborateur bigint NOT NULL,
    type_collaborateur character varying(31) NOT NULL,
    nom character varying(50) NOT NULL,
    prenom character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    mot_de_passe character varying(255) NOT NULL,
    CONSTRAINT collaborateur_type_collaborateur_check CHECK (((type_collaborateur)::text = ANY ((ARRAY['Collaborateur'::character varying, 'EMPLOYE'::character varying, 'MANAGER'::character varying])::text[])))
);

ALTER TABLE public.collaborateur ALTER COLUMN id_collaborateur ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaborateur_id_collaborateur_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.employe (
    id_collaborateur bigint NOT NULL,
    id_manager bigint
);

CREATE TABLE public.imputation (
    date_validation timestamp(6) without time zone,
    id_employe bigint NOT NULL,
    id_imputation bigint NOT NULL,
    id_manager_validateur bigint,
    id_projet bigint NOT NULL,
    nom character varying(100) NOT NULL,
    statut character varying(255) NOT NULL,
    date_imputation date,
    heures double precision,
    motif_rejet character varying(500),
    CONSTRAINT imputation_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'VALIDEE'::character varying, 'REJETEE'::character varying])::text[])))
);

ALTER TABLE public.imputation ALTER COLUMN id_imputation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imputation_id_imputation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.manager (
    id_collaborateur bigint NOT NULL
);

CREATE TABLE public.projet (
    date_debut date,
    date_fin date,
    id_client bigint NOT NULL,
    id_projet bigint NOT NULL,
    type_projet character varying(31) NOT NULL,
    nom character varying(100) NOT NULL,
    CONSTRAINT projet_type_projet_check CHECK (((type_projet)::text = ANY ((ARRAY['PROJET'::character varying, 'BUDGET'::character varying])::text[])))
);

ALTER TABLE public.projet ALTER COLUMN id_projet ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projet_id_projet_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.quota_absence (
    annee integer NOT NULL,
    jours_alloues double precision NOT NULL,
    jours_pris double precision NOT NULL,
    id_employe bigint NOT NULL,
    id_quota bigint NOT NULL,
    type_absence character varying(40) NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT quota_absence_type_absence_check CHECK (((type_absence)::text = ANY ((ARRAY['CONGE_PAYE'::character varying, 'RTT'::character varying, 'CONGE_EXCEPTIONNEL'::character varying, 'MALADIE'::character varying, 'CONGE_MATERNITE_PATERNITE'::character varying, 'SANS_SOLDE'::character varying])::text[])))
);

ALTER TABLE public.quota_absence ALTER COLUMN id_quota ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quota_absence_id_quota_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.absence
    ADD CONSTRAINT absence_pkey PRIMARY KEY (id_absence);

ALTER TABLE ONLY public.affectation
    ADD CONSTRAINT affectation_pkey PRIMARY KEY (id_collaborateur, id_projet);

ALTER TABLE ONLY public.budget_projet
    ADD CONSTRAINT budget_projet_pkey PRIMARY KEY (id_projet);

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id_client);

ALTER TABLE ONLY public.collaborateur
    ADD CONSTRAINT collaborateur_email_key UNIQUE (email);

ALTER TABLE ONLY public.collaborateur
    ADD CONSTRAINT collaborateur_pkey PRIMARY KEY (id_collaborateur);

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT employe_pkey PRIMARY KEY (id_collaborateur);

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT imputation_pkey PRIMARY KEY (id_imputation);

ALTER TABLE ONLY public.manager
    ADD CONSTRAINT manager_pkey PRIMARY KEY (id_collaborateur);

ALTER TABLE ONLY public.projet
    ADD CONSTRAINT projet_pkey PRIMARY KEY (id_projet);

ALTER TABLE ONLY public.quota_absence
    ADD CONSTRAINT quota_absence_pkey PRIMARY KEY (id_quota);

ALTER TABLE ONLY public.quota_absence
    ADD CONSTRAINT uk_quota_employe_type_annee UNIQUE (id_employe, type_absence, annee);

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fk20leac5lv2j205741kdn7hqga FOREIGN KEY (id_collaborateur) REFERENCES public.collaborateur(id_collaborateur);

ALTER TABLE ONLY public.manager
    ADD CONSTRAINT fk465egn6wegrx7ld777oxalr13 FOREIGN KEY (id_collaborateur) REFERENCES public.collaborateur(id_collaborateur);

ALTER TABLE ONLY public.affectation
    ADD CONSTRAINT fk65970vomad0q62yana3l7pa31 FOREIGN KEY (id_collaborateur) REFERENCES public.collaborateur(id_collaborateur);

ALTER TABLE ONLY public.budget_projet
    ADD CONSTRAINT fk81f3ijdaagp5vj9rwmsig9lus FOREIGN KEY (id_projet) REFERENCES public.projet(id_projet);

ALTER TABLE ONLY public.quota_absence
    ADD CONSTRAINT fkbf53o0tjxke1hq2sqxdsiwtql FOREIGN KEY (id_employe) REFERENCES public.collaborateur(id_collaborateur);

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkg963xhr555de213891a8guvwa FOREIGN KEY (id_manager) REFERENCES public.manager(id_collaborateur);

ALTER TABLE ONLY public.projet
    ADD CONSTRAINT fkhquklcvgo5vxr5mr8bj1g6ln8 FOREIGN KEY (id_client) REFERENCES public.client(id_client);

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT fkjnufo9p1beu2d6i9gwb7xdg6k FOREIGN KEY (id_projet) REFERENCES public.projet(id_projet);

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT fkk3w87tm0jri1luo7khgvqtjuu FOREIGN KEY (id_employe) REFERENCES public.employe(id_collaborateur);

ALTER TABLE ONLY public.absence
    ADD CONSTRAINT fkmuupojf0q839e0k2o8rq5q5pa FOREIGN KEY (id_manager_validateur) REFERENCES public.manager(id_collaborateur);

ALTER TABLE ONLY public.absence
    ADD CONSTRAINT fkpsolykjdea7j9qoms3g16b3ty FOREIGN KEY (id_employe) REFERENCES public.collaborateur(id_collaborateur);

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT fkrm06tnl6m98c0irh4ft38h4ab FOREIGN KEY (id_manager_validateur) REFERENCES public.manager(id_collaborateur);

ALTER TABLE ONLY public.affectation
    ADD CONSTRAINT fkryjr8cppkto7uwxffw9ngvyn FOREIGN KEY (id_projet) REFERENCES public.projet(id_projet);


